name: Build GitHub and Deploy to VDS (Sprintbox)

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
        YANDEX_MAPS_API: ${{ secrets.YANDEX_MAPS_API }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_ADMIN_CHAT_ID: ${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Archive production files
        run: |
          mkdir deploy
          cp -r .next deploy/
          cp -r public deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp ecosystem.config.js deploy/

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 -H ${{ secrets.VDS_HOST }} >> ~/.ssh/known_hosts

      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'deploy/*'
          target: '/var/www/site'
          strip_components: 1
          
      - name: Setup environment and install deps on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/site
            echo "YANDEX_MAPS_API=${{ secrets.YANDEX_MAPS_API }}" > .env.local
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env.local
            echo "TELEGRAM_ADMIN_CHAT_ID=${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}" >> .env.local
            npm ci --omit=dev

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/site
            pm2 startOrReload ecosystem.config.js --only site
