name: Build GitHub and Deploy to VDS (Sprintbox)

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
        YANDEX_MAPS_API: ${{ secrets.YANDEX_MAPS_API }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_ADMIN_CHAT_ID: ${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}
        
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Archive production files
        run: |
          mkdir deploy
          cp -r .next deploy/
          cp -r public deploy/
          cp -r node_modules deploy/
          cp -r package.json deploy/
          cp -r ecosystem.config.js deploy/

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VDS_HOST }} >> ~/.ssh/known_hosts

      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'deploy/*'
          target: '/var/www/site'
          strip_components: 1

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/site
            pm2 reload ecosystem.config.js --only site || pm2 start ecosystem.config.js --only site || true
